//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DartsApp.Resources.Translations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DartsAppTranslations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DartsAppTranslations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DartsApp.Resources.Translations.DartsAppTranslations", typeof(DartsAppTranslations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average.
        /// </summary>
        internal static string Average {
            get {
                return ResourceManager.GetString("Average", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose language.
        /// </summary>
        internal static string ChangeLanguage_Title {
            get {
                return ResourceManager.GetString("ChangeLanguage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marks per round.
        /// </summary>
        internal static string CricketStatisticsView_MarksPerRound {
            get {
                return ResourceManager.GetString("CricketStatisticsView_MarksPerRound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rounds to win.
        /// </summary>
        internal static string CricketStatisticsView_RoundsToWin {
            get {
                return ResourceManager.GetString("CricketStatisticsView_RoundsToWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average.
        /// </summary>
        internal static string CricketStatisticsViewModel_Average {
            get {
                return ResourceManager.GetString("CricketStatisticsViewModel_Average", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum.
        /// </summary>
        internal static string CricketStatisticsViewModel_Maximum {
            get {
                return ResourceManager.GetString("CricketStatisticsViewModel_Maximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum.
        /// </summary>
        internal static string CricketStatisticsViewModel_Minimum {
            get {
                return ResourceManager.GetString("CricketStatisticsViewModel_Minimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classic.
        /// </summary>
        internal static string CricketType_Classic {
            get {
                return ResourceManager.GetString("CricketType_Classic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random numbers.
        /// </summary>
        internal static string CricketType_RandomNumbers {
            get {
                return ResourceManager.GetString("CricketType_RandomNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whiny Kid.
        /// </summary>
        internal static string DartsBot1 {
            get {
                return ResourceManager.GetString("DartsBot1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bob.
        /// </summary>
        internal static string DartsBot10 {
            get {
                return ResourceManager.GetString("DartsBot10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Darts Club Champion.
        /// </summary>
        internal static string DartsBot11 {
            get {
                return ResourceManager.GetString("DartsBot11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hawk Eye.
        /// </summary>
        internal static string DartsBot12 {
            get {
                return ResourceManager.GetString("DartsBot12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Robin Hood.
        /// </summary>
        internal static string DartsBot13 {
            get {
                return ResourceManager.GetString("DartsBot13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green Arrow.
        /// </summary>
        internal static string DartsBot14 {
            get {
                return ResourceManager.GetString("DartsBot14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City Champion.
        /// </summary>
        internal static string DartsBot15 {
            get {
                return ResourceManager.GetString("DartsBot15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regional Champion.
        /// </summary>
        internal static string DartsBot16 {
            get {
                return ResourceManager.GetString("DartsBot16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to National Champion.
        /// </summary>
        internal static string DartsBot17 {
            get {
                return ResourceManager.GetString("DartsBot17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fallon Sherrock.
        /// </summary>
        internal static string DartsBot18 {
            get {
                return ResourceManager.GetString("DartsBot18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dimitri van den Bergh.
        /// </summary>
        internal static string DartsBot19 {
            get {
                return ResourceManager.GetString("DartsBot19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arthritic Grandma.
        /// </summary>
        internal static string DartsBot2 {
            get {
                return ResourceManager.GetString("DartsBot2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Luke Littler.
        /// </summary>
        internal static string DartsBot20 {
            get {
                return ResourceManager.GetString("DartsBot20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drunken Homeless Guy.
        /// </summary>
        internal static string DartsBot3 {
            get {
                return ResourceManager.GetString("DartsBot3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double-Zero Daniel.
        /// </summary>
        internal static string DartsBot4 {
            get {
                return ResourceManager.GetString("DartsBot4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Board-Breaking Billie.
        /// </summary>
        internal static string DartsBot5 {
            get {
                return ResourceManager.GetString("DartsBot5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Throwing Ted.
        /// </summary>
        internal static string DartsBot6 {
            get {
                return ResourceManager.GetString("DartsBot6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dart Hall Cleaner.
        /// </summary>
        internal static string DartsBot7 {
            get {
                return ResourceManager.GetString("DartsBot7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Darts Shop Owner.
        /// </summary>
        internal static string DartsBot8 {
            get {
                return ResourceManager.GetString("DartsBot8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Pub Hero.
        /// </summary>
        internal static string DartsBot9 {
            get {
                return ResourceManager.GetString("DartsBot9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double in.
        /// </summary>
        internal static string DoubleIn {
            get {
                return ResourceManager.GetString("DoubleIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double out.
        /// </summary>
        internal static string DoubleOut {
            get {
                return ResourceManager.GetString("DoubleOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0&apos;s.
        /// </summary>
        internal static string DoublesPracticeViewModel_0s {
            get {
                return ResourceManager.GetString("DoublesPracticeViewModel_0s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add at least one player.
        /// </summary>
        internal static string Error_SelectGameViewModel_AddMorePlayers {
            get {
                return ResourceManager.GetString("Error_SelectGameViewModel_AddMorePlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error_Title {
            get {
                return ResourceManager.GetString("Error_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What would you like to do?.
        /// </summary>
        internal static string MainPage_HeaderText {
            get {
                return ResourceManager.GetString("MainPage_HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New game.
        /// </summary>
        internal static string MainPage_NewGame {
            get {
                return ResourceManager.GetString("MainPage_NewGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        internal static string MainPage_Statistics {
            get {
                return ResourceManager.GetString("MainPage_Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training.
        /// </summary>
        internal static string MainPage_Training {
            get {
                return ResourceManager.GetString("MainPage_Training", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select player.
        /// </summary>
        internal static string MainViewModel_SelectPlayer {
            get {
                return ResourceManager.GetString("MainViewModel_SelectPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master in.
        /// </summary>
        internal static string MasterIn {
            get {
                return ResourceManager.GetString("MasterIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master out.
        /// </summary>
        internal static string MasterOut {
            get {
                return ResourceManager.GetString("MasterOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        internal static string Off {
            get {
                return ResourceManager.GetString("Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        internal static string On {
            get {
                return ResourceManager.GetString("On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player.
        /// </summary>
        internal static string Player {
            get {
                return ResourceManager.GetString("Player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new player.
        /// </summary>
        internal static string PlayerListView_Add {
            get {
                return ResourceManager.GetString("PlayerListView_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove player.
        /// </summary>
        internal static string PlayerListView_Remove {
            get {
                return ResourceManager.GetString("PlayerListView_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Players.
        /// </summary>
        internal static string PlayerListView_Title {
            get {
                return ResourceManager.GetString("PlayerListView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joe.
        /// </summary>
        internal static string PlayerListViewModel_NewPlayer_PlaceHolder {
            get {
                return ResourceManager.GetString("PlayerListViewModel_NewPlayer_PlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new player.
        /// </summary>
        internal static string PlayerListViewModel_NewPlayer_Text {
            get {
                return ResourceManager.GetString("PlayerListViewModel_NewPlayer_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New player.
        /// </summary>
        internal static string PlayerListViewModel_NewPlayer_Title {
            get {
                return ResourceManager.GetString("PlayerListViewModel_NewPlayer_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing this player will permanently delete all their played matches from the statistics..
        /// </summary>
        internal static string PlayerListViewModel_RemoveConfirmation_Text {
            get {
                return ResourceManager.GetString("PlayerListViewModel_RemoveConfirmation_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        internal static string PlayerListViewModel_RemoveConfirmation_Title {
            get {
                return ResourceManager.GetString("PlayerListViewModel_RemoveConfirmation_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A player with this name already exists.
        /// </summary>
        internal static string PlayerListViewModel_WrongName_Text {
            get {
                return ResourceManager.GetString("PlayerListViewModel_WrongName_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong name.
        /// </summary>
        internal static string PlayerListViewModel_WrongName_Title {
            get {
                return ResourceManager.GetString("PlayerListViewModel_WrongName_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkout.
        /// </summary>
        internal static string Practice121View_Checkout {
            get {
                return ResourceManager.GetString("Practice121View_Checkout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkpoint.
        /// </summary>
        internal static string Practice121View_Checkpoint {
            get {
                return ResourceManager.GetString("Practice121View_Checkpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Round.
        /// </summary>
        internal static string Practice121View_Round {
            get {
                return ResourceManager.GetString("Practice121View_Round", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score.
        /// </summary>
        internal static string Practice121View_Score {
            get {
                return ResourceManager.GetString("Practice121View_Score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doubles: .
        /// </summary>
        internal static string ScoringPracticeView_Doubles {
            get {
                return ResourceManager.GetString("ScoringPracticeView_Doubles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Misses: .
        /// </summary>
        internal static string ScoringPracticeView_Misses {
            get {
                return ResourceManager.GetString("ScoringPracticeView_Misses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sectors: .
        /// </summary>
        internal static string ScoringPracticeView_Sectors {
            get {
                return ResourceManager.GetString("ScoringPracticeView_Sectors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trebles: .
        /// </summary>
        internal static string ScoringPracticeView_Trebles {
            get {
                return ResourceManager.GetString("ScoringPracticeView_Trebles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations.
        /// </summary>
        internal static string ScoringPracticeViewModel_Congratulations {
            get {
                return ResourceManager.GetString("ScoringPracticeViewModel_Congratulations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double.
        /// </summary>
        internal static string ScoringPracticeViewModel_Double {
            get {
                return ResourceManager.GetString("ScoringPracticeViewModel_Double", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You finished the training!.
        /// </summary>
        internal static string ScoringPracticeViewModel_FinishedTraining {
            get {
                return ResourceManager.GetString("ScoringPracticeViewModel_FinishedTraining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sector.
        /// </summary>
        internal static string ScoringPracticeViewModel_Sector {
            get {
                return ResourceManager.GetString("ScoringPracticeViewModel_Sector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single.
        /// </summary>
        internal static string ScoringPracticeViewModel_Single {
            get {
                return ResourceManager.GetString("ScoringPracticeViewModel_Single", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Triple.
        /// </summary>
        internal static string ScoringPracticeViewModel_Triple {
            get {
                return ResourceManager.GetString("ScoringPracticeViewModel_Triple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legs.
        /// </summary>
        internal static string SelectGameView_Legs {
            get {
                return ResourceManager.GetString("SelectGameView_Legs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points.
        /// </summary>
        internal static string SelectGameView_Points {
            get {
                return ResourceManager.GetString("SelectGameView_Points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets.
        /// </summary>
        internal static string SelectGameView_Sets {
            get {
                return ResourceManager.GetString("SelectGameView_Sets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string SelectGameView_Start {
            get {
                return ResourceManager.GetString("SelectGameView_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add bot.
        /// </summary>
        internal static string SelectGameViewModel_AddBot {
            get {
                return ResourceManager.GetString("SelectGameViewModel_AddBot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add player.
        /// </summary>
        internal static string SelectGameViewModel_AddPlayer {
            get {
                return ResourceManager.GetString("SelectGameViewModel_AddPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doubles.
        /// </summary>
        internal static string SelectTrainingView_Doubles {
            get {
                return ResourceManager.GetString("SelectTrainingView_Doubles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What do you wish to practice?.
        /// </summary>
        internal static string SelectTrainingView_HeaderText {
            get {
                return ResourceManager.GetString("SelectTrainingView_HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scoring.
        /// </summary>
        internal static string SelectTrainingView_Scoring {
            get {
                return ResourceManager.GetString("SelectTrainingView_Scoring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Straight in.
        /// </summary>
        internal static string StraightIn {
            get {
                return ResourceManager.GetString("StraightIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Straight out.
        /// </summary>
        internal static string StraightOut {
            get {
                return ResourceManager.GetString("StraightOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkout darts used.
        /// </summary>
        internal static string X01GameViewModel_CheckoutDartsUsed {
            get {
                return ResourceManager.GetString("X01GameViewModel_CheckoutDartsUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Darts used.
        /// </summary>
        internal static string X01GameViewModel_DartsUsed {
            get {
                return ResourceManager.GetString("X01GameViewModel_DartsUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This score is not valid.
        /// </summary>
        internal static string X01GameViewModel_WrongScorePopup_Text {
            get {
                return ResourceManager.GetString("X01GameViewModel_WrongScorePopup_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong score.
        /// </summary>
        internal static string X01GameViewModel_WrongScorePopup_Title {
            get {
                return ResourceManager.GetString("X01GameViewModel_WrongScorePopup_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Big throws.
        /// </summary>
        internal static string X01StatisticsView_BigThrows {
            get {
                return ResourceManager.GetString("X01StatisticsView_BigThrows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkout.
        /// </summary>
        internal static string X01StatisticsView_Checkout {
            get {
                return ResourceManager.GetString("X01StatisticsView_Checkout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 darts avg..
        /// </summary>
        internal static string X01StatisticsViewModel_3DartAverage {
            get {
                return ResourceManager.GetString("X01StatisticsViewModel_3DartAverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First 9 darts avg..
        /// </summary>
        internal static string X01StatisticsViewModel_9DartAverage {
            get {
                return ResourceManager.GetString("X01StatisticsViewModel_9DartAverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best leg darts.
        /// </summary>
        internal static string X01StatisticsViewModel_BestLeg {
            get {
                return ResourceManager.GetString("X01StatisticsViewModel_BestLeg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highest checkout.
        /// </summary>
        internal static string X01StatisticsViewModel_HighestCheckout {
            get {
                return ResourceManager.GetString("X01StatisticsViewModel_HighestCheckout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highest score.
        /// </summary>
        internal static string X01StatisticsViewModel_HighestScore {
            get {
                return ResourceManager.GetString("X01StatisticsViewModel_HighestScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legs won.
        /// </summary>
        internal static string X01StatisticsViewModel_LegsWon {
            get {
                return ResourceManager.GetString("X01StatisticsViewModel_LegsWon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly.
        /// </summary>
        internal static string X01StatisticsViewModel_Monthly {
            get {
                return ResourceManager.GetString("X01StatisticsViewModel_Monthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string X01StatisticsViewModel_Total {
            get {
                return ResourceManager.GetString("X01StatisticsViewModel_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekly.
        /// </summary>
        internal static string X01StatisticsViewModel_Weekly {
            get {
                return ResourceManager.GetString("X01StatisticsViewModel_Weekly", resourceCulture);
            }
        }
    }
}
